name: Build-WeChatFerry-SDK

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level to use'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Visual Studio 2019
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: "16.0" # 16.x 对应 Visual Studio 2019

      - name: 设置缓存
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: |
            C:/Tools/vcpkg
            ${{ github.workspace }}/WeChatFerry/vcpkg_installed
          key: vcpkg-${{ hashFiles('WeChatFerry/vcpkg.json') }}
          restore-keys: |
            vcpkg-

      - name: 安装 vcpkg 并初始化依赖项
        run: |
          if (!(Test-Path -Path 'C:/Tools')) {
            New-Item -ItemType Directory -Force -Path 'C:/Tools'
          }
          cd C:/Tools
          if (!(Test-Path -Path 'C:/Tools/vcpkg')) {
            git clone https://github.com/microsoft/vcpkg
          }
          .\vcpkg\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=C:/Tools/vcpkg" >> $GITHUB_ENV
          $env:VCPKG_ROOT = 'C:/Tools/vcpkg'
          cd ${{ github.workspace }}/WeChatFerry
          C:/Tools/vcpkg/vcpkg install --triplet x64-windows-static
          C:/Tools/vcpkg/vcpkg integrate install

      - name: 构建 sdk.dll
        run: |
          msbuild WeChatFerry/sdk.vcxproj `
            /p:Configuration=Release `
            /p:Platform="x64" `
            /p:VcpkgTriplet="x64-windows-static" `
            /p:VcpkgEnableManifest=true `
            /verbosity:minimal
        shell: pwsh

      - name: 复制 sdk.dll 到仓库根目录的 dll 文件夹
        run: |
          New-Item -ItemType Directory -Force -Path "${{ github.workspace }}/dll"
          Copy-Item -Path "WeChatFerry/Out/sdk.dll" -Destination "${{ github.workspace }}/dll/sdk.dll" -Force
        shell: pwsh

      - name: 打包 sdk.dll
        run: |
          New-Item -ItemType Directory -Force -Path "WeChatFerry/tmp"
          Compress-Archive -Path "WeChatFerry/Out/sdk.dll" -DestinationPath "WeChatFerry/tmp/sdk.zip"
        shell: pwsh

      - name: 提交更改到仓库
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dll/sdk.dll
          git commit -m "Update sdk.dll in dll folder"
          git push
        shell: pwsh

      - name: 发布 sdk.dll 到 Github Releases
        uses: ncipollo/release-action@main
        with:
          name: sdk-release
          tag: sdk-latest
          token: ${{ secrets.REPO_TOKEN }}
          allowUpdates: true
          artifacts: "WeChatFerry/tmp/sdk.zip"
          body: |
            sdk.dll 构建版本
